import finger
import FreeCAD as App
import utils

# This is needed for development since FreeCAD uses cached version of library.
import importlib
importlib.reload(finger)

doc = App.ActiveDocument

name = 'dot'
utils.clear_report()
utils.remove_clones(doc, name)

if not hasattr(doc, name):
    doc.addObject("Part::Sphere", name)

box = doc.getObject(name)
doc.recompute()

h = finger.Hand()
for f, offset in zip(h.fingers, h.offsets):
    for r in f.rows:
        c_box = doc.copyObject(box)
        c_box.Placement = App.Placement(f.get_pos(r, offset=offset),
                                        App.Rotation(0, 0, 0),
                                        App.Vector(5, 5, 5))
        doc.recompute()
        print(c_box.Name, c_box.Placement)

# TODO: Copy and place a grid of these boxes.
doc.recompute()
